version: '3'
services:
  # Server Statistics Collection Service
  server_statistics_collection_service:
    image: stat-image
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - rabbitmq

  # Consumer Service
  consumer_service:
    image: consume
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - rabbitmq

  # MongoDB
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # RabbitMQ
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "8080:15672"
      - "5672:5672"
    hostname: rabbitmq

  # Mongo Express
  mongo_express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
