# Use the official .NET 6 SDK as a parent image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ConsumerService.csproj", "./"]
RUN dotnet restore "ConsumerService.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "ConsumerService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConsumerService.csproj" -c Release -o /app/publish

# Use the official .NET 6 runtime as a base image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=publish /app/publish .
ENV MemoryUsageAnomalyThresholdPercentage=0.4
ENV CpuUsageAnomalyThresholdPercentage=0.5
ENV MemoryUsageThresholdPercentage=0.8
ENV CpuUsageThresholdPercentage=0.9
ENV SignalRUrl=http://your-signalr-hub-url
ENV MongoDBConnectionString=mongodb://mongo:27017
ENV MongoDBDatabaseName=ServerMonitoring
ENV MongoServerStatCollection=ServerStatistics
ENTRYPOINT ["dotnet", "ConsumerService.dll"]
